name: Build Windows Binary
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: marler8997/setup-zig@v0.8
        with:
          zig-version: "0.14.1"

      - name: Build dispatch
        run: zig build -Doptimize=ReleaseSafe run-dispatch

      - name: Build gameserver
        run: zig build -Doptimize=ReleaseSafe run-gameserver

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-windows
          path: zig-out/bin/*.exe
